#include "s21_string.h"
char *errorList[MAX_ERRLIST] = {
    "Success",
    "Operation not permitted",
    "No such file or directory",
    "No such process",
    "Interrupted system call",
    "Input/output error",
    "No such device or address",
    "Argument list too long",
    "Exec format error",
    "Bad file descriptor",
    "No child processes",
    "Resource temporarily unavailable",
    "Cannot allocate memory",
    "Permission denied",
    "Bad address",
    "Block device required",
    "Device or resource busy",
    "File exists",
    "Invalid cross-device link",
    "No such device",
    "Not a directory",
    "Is a directory",
    "Invalid argument",
    "Too many open files in system",
    "Too many open files",
    "Inappropriate ioctl for device",
    "Text file busy",
    "File too large",
    "No space left on device",
    "Illegal seek",
    "Read-only file system",
    "Too many links",
    "Broken pipe",
    "Numerical argument out of domain",
    "Numerical result out of range",
    "Resource deadlock avoided",
    "File name too long",
    "No locks available",
    "Function not implemented",
    "Directory not empty",
    "Too many levels of symbolic links",
    "Unknown error 41",
    "No message of desired type",
    "Identifier removed",
    "Channel number out of range",
    "Level 2 not synchronized",
    "Level 3 halted",
    "Level 3 reset",
    "Link number out of range",
    "Protocol driver not attached",
    "No CSI structure available",
    "Level 2 halted",
    "Invalid exchange",
    "Invalid request descriptor",
    "Exchange full",
    "No anode",
    "Invalid request code",
    "Invalid slot",
    "Unknown error 58",
    "Bad font file format",
    "Device not a stream",
    "No data available",
    "Timer expired",
    "Out of streams resources",
    "Machine is not on the network",
    "Package not installed",
    "Object is remote",
    "Link has been severed",
    "Advertise error",
    "Srmount error",
    "Communication error on send",
    "Protocol error",
    "Multihop attempted",
    "RFS specific error",
    "Bad message",
    "Value too large for defined data type",
    "Name not unique on network",
    "File descriptor in bad state",
    "Remote address changed",
    "Can not access a needed shared library",
    "Accessing a corrupted shared library",
    ".lib section in a.out corrupted",
    "Attempting to link in too many shared libraries",
    "Cannot exec a shared library directly",
    "Invalid or incomplete multibyte or wide character",
    "Interrupted system call should be restarted",
    "Streams pipe error",
    "Too many users",
    "Socket operation on non-socket",
    "Destination address required",
    "Message too long",
    "Protocol wrong type for socket",
    "Protocol not available",
    "Protocol not supported",
    "Socket type not supported",
    "Operation not supported",
    "Protocol family not supported",
    "Address family not supported by protocol",
    "Address already in use",
    "Cannot assign requested address",
    "Network is down",
    "Network is unreachable",
    "Network dropped connection on reset",
    "Software caused connection abort",
    "Connection reset by peer",
    "No buffer space available",
    "Transport endpoint is already connected",
    "Transport endpoint is not connected",
    "Cannot send after transport endpoint shutdown",
    "Too many references: cannot splice",
    "Connection timed out",
    "Connection refused",
    "Host is down",
    "No route to host",
    "Operation already in progress",
    "Operation now in progress",
    "Stale file handle",
    "Structure needs cleaning",
    "Not a XENIX named type file",
    "No XENIX semaphores available",
    "Is a named type file",
    "Remote I/O error",
    "Disk quota exceeded",
    "No medium found",
    "Wrong medium type",
    "Operation canceled",
    "Required key not available",
    "Key has expired",
    "Key has been revoked",
    "Key was rejected by service",
    "Owner died",
    "State not recoverable",
    "Operation not possible due to RF-kill",
    "Memory page has hardware error",
    "Unknown error 134",
    "Unknown error 135",
    "Unknown error 136",
    "Unknown error 137",
    "Unknown error 138",
    "Unknown error 139",
    "Unknown error 140",
    "Unknown error 141",
    "Unknown error 142",
    "Unknown error 143",
    "Unknown error 144",
    "Unknown error 145",
    "Unknown error 146",
    "Unknown error 147",
    "Unknown error 148",
    "Unknown error 149",
    "Unknown error 150",
    "Unknown error 151",
    "Unknown error 152",
    "Unknown error 153",
    "Unknown error 154",
    "Unknown error 155",
    "Unknown error 156",
    "Unknown error 157",
    "Unknown error 158",
    "Unknown error 159",
    "Unknown error 160",
    "Unknown error 161",
    "Unknown error 162",
    "Unknown error 163",
    "Unknown error 164",
    "Unknown error 165",
    "Unknown error 166",
    "Unknown error 167",
    "Unknown error 168",
    "Unknown error 169",
    "Unknown error 170",
    "Unknown error 171",
    "Unknown error 172",
    "Unknown error 173",
    "Unknown error 174",
    "Unknown error 175",
    "Unknown error 176",
    "Unknown error 177",
    "Unknown error 178",
    "Unknown error 179",
    "Unknown error 180",
    "Unknown error 181",
    "Unknown error 182",
    "Unknown error 183",
    "Unknown error 184",
    "Unknown error 185",
    "Unknown error 186",
    "Unknown error 187",
    "Unknown error 188",
    "Unknown error 189",
    "Unknown error 190",
    "Unknown error 191",
    "Unknown error 192",
    "Unknown error 193",
    "Unknown error 194",
    "Unknown error 195",
    "Unknown error 196",
    "Unknown error 197",
    "Unknown error 198",
    "Unknown error 199",
    "Unknown error 200",
    "Unknown error 201",
    "Unknown error 202",
    "Unknown error 203",
    "Unknown error 204",
    "Unknown error 205",
    "Unknown error 206",
    "Unknown error 207",
    "Unknown error 208",
    "Unknown error 209",
    "Unknown error 210",
    "Unknown error 211",
    "Unknown error 212",
    "Unknown error 213",
    "Unknown error 214",
    "Unknown error 215",
    "Unknown error 216",
    "Unknown error 217",
    "Unknown error 218",
    "Unknown error 219",
    "Unknown error 220",
    "Unknown error 221",
    "Unknown error 222",
    "Unknown error 223",
    "Unknown error 224",
    "Unknown error 225",
    "Unknown error 226",
    "Unknown error 227",
    "Unknown error 228",
    "Unknown error 229",
    "Unknown error 230",
    "Unknown error 231",
    "Unknown error 232",
    "Unknown error 233",
    "Unknown error 234",
    "Unknown error 235",
    "Unknown error 236",
    "Unknown error 237",
    "Unknown error 238",
    "Unknown error 239",
    "Unknown error 240",
    "Unknown error 241",
    "Unknown error 242",
    "Unknown error 243",
    "Unknown error 244",
    "Unknown error 245",
    "Unknown error 246",
    "Unknown error 247",
    "Unknown error 248",
    "Unknown error 249",
    "Unknown error 250",
    "Unknown error 251",
    "Unknown error 252",
    "Unknown error 253",
    "Unknown error 254",
    "Unknown error 255",
};

char *s21_strerror(int errorNumber) {
  static char result[512] = {'\0'};

  if (errorNumber >= 0 && errorNumber < MAX_ERRLIST) {
    snprintf(result, sizeof(result), "%s", errorList[errorNumber]);
  } else {
    snprintf(result, sizeof(result), "Unknown error %d", errorNumber);
  }

  return result;
}